apiVersion: v1
kind: Service
metadata:
  name: jvm-service
  namespace: paas
spec:
  selector:
    k8s-app: jvmv
  ports:
    - port: 7777
      targetPort: 8080
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jvm-deployment
  namespace: paas
  labels:
    k8s-app: jvmv
spec:
  replicas: 1
  template:
    metadata:
      name:  jvmviewer-pod
      namespace: paas
      labels:
        k8s-app: jvmv
    spec:
      containers:
        - name: jvmv
          image: docker.cloudos.yihecloud.com/openbridge/jvmviewer:1.0